<?php if($page=="about"){ ?>
<title>T-Series Stage Works &bull; About</title>
<meta name="keywords" content="T-Series, tseries acting academy, Tseries singing academy, Tseries Modelling academy, Tseries Dance academy, tseries photography academy, tseries instrumental academy, tseries acting school, Tseries singing school, Tseries Modelling school, Tseries Dance school, tseries photography school, tseries instrumental school, tseries music school, acting school in noida, singing school in noida, best acting school in delhi, best acting school in noida, best singing school in noida, best singing school in delhi, best acting academy in noida, best acting academy in delhi, best singing school in noida, best singing school in delhi, best dancing school in noida, best dancing school in delhi, acting school in delhi, singing school in delhi, best acting class in noida, best acting classes in delhi">
<meta name="description" content="The T-Series StageWorks Academy is a joint-venture initiative designed to identify, nurture and create a pool of immensely skilful and passionate professionals who can match national and global demands.">
<?php } else if($page=="application-form"){ ?>
<title>T-Series Stage Works &bull; Application Form</title>
<meta name="keywords" content="T-Series, tseries acting academy, Tseries singing academy, Tseries Modelling academy, Tseries Dance academy, tseries photography academy, tseries instrumental academy, tseries acting school, Tseries singing school, Tseries Modelling school, Tseries Dance school, tseries photography school, tseries instrumental school, tseries music school, acting school in noida, singing school in noida, best acting school in delhi, best acting school in noida, best singing school in noida, best singing school in delhi, best acting academy in noida, best acting academy in delhi, best singing school in noida, best singing school in delhi, best dancing school in noida, best dancing school in delhi, acting school in delhi, singing school in delhi, best acting class in noida, best acting classes in delhi">
<meta name="description" content="Application for Admission">
<?php } else if($page=="campus"){ ?>
<title>T-Series Stage Works &bull; Campus</title>
<meta name="keywords" content="T-Series, tseries acting academy, Tseries singing academy, Tseries Modelling academy, Tseries Dance academy, tseries photography academy, tseries instrumental academy, tseries acting school, Tseries singing school, Tseries Modelling school, Tseries Dance school, tseries photography school, tseries instrumental school, tseries music school, acting school in noida, singing school in noida, best acting school in delhi, best acting school in noida, best singing school in noida, best singing school in delhi, best acting academy in noida, best acting academy in delhi, best singing school in noida, best singing school in delhi, best dancing school in noida, best dancing school in delhi, acting school in delhi, singing school in delhi, best acting class in noida, best acting classes in delhi">
<meta name="description" content="At our new campus in sector 62, Noida, we are located at a strategic location which is only a few minutes away from the prime localities of Noida, Mayur Vihar, Vaishali, Indirapuram, Laxmi Nagar, Kaushambi, Ghaziabad etc. Adjacent to the NH24 highway, it is within 5-7 minutes driving range from Delhi.
">
<?php } else if($page=="contact"){ ?>
<title>T-Series Stage Works &bull; Contact</title>
<meta name="keywords" content="T-Series, tseries acting academy, Tseries singing academy, Tseries Modelling academy, Tseries Dance academy, tseries photography academy, tseries instrumental academy, tseries acting school, Tseries singing school, Tseries Modelling school, Tseries Dance school, tseries photography school, tseries instrumental school, tseries music school, acting school in noida, singing school in noida, best acting school in delhi, best acting school in noida, best singing school in noida, best singing school in delhi, best acting academy in noida, best acting academy in delhi, best singing school in noida, best singing school in delhi, best dancing school in noida, best dancing school in delhi, acting school in delhi, singing school in delhi, best acting class in noida, best acting classes in delhi">
<meta name="description" content="">
<?php } else if($page=="programs"){ ?>
<title>T-Series Stage Works &bull; Programs</title>
<meta name="keywords" content="T-Series, tseries acting academy, Tseries singing academy, Tseries Modelling academy, Tseries Dance academy, tseries photography academy, tseries instrumental academy, tseries acting school, Tseries singing school, Tseries Modelling school, Tseries Dance school, tseries photography school, tseries instrumental school, tseries music school, acting school in noida, singing school in noida, best acting school in delhi, best acting school in noida, best singing school in noida, best singing school in delhi, best acting academy in noida, best acting academy in delhi, best singing school in noida, best singing school in delhi, best dancing school in noida, best dancing school in delhi, acting school in delhi, singing school in delhi, best acting class in noida, best acting classes in delhi">
<meta name="description" content="">
<?php } else if($page=="basics-of-acting"){ ?>
<title>T-Series Stage Works &bull; Programs &bull; Basics of Acting</title>
<meta name="keywords" content="tseries acting academy, acting school in noida, best acting school in noida, acting school in delhi, best acting shool in delhi, acting academy in noida, acting academy in noida, best acting class in noida, best acting classes in delhi, acting institute in noida, best acting institute in noida, acting institute in delhi, best acting institue in delhi">
<meta name="description" content="Enroll in one of the Best Acting School in Noida. T-Series StageWorks is the best acting school in Delhi">
<?php } else if($page=="basics-of-singing"){ ?>
<title>T-Series Stage Works &bull; Programs &bull; Basics of Singing</title>
<meta name="keywords" content="Tseries singing academy, Tseries singing school, singing school in noida, best acting school in delhi, best acting school in noida, best singing school in noida, best singing school in delhi, best acting academy in noida, best acting academy in delhi, best singing school in noida, best singing school in delhi, acting school in delhi, singing school in delhi, best acting class in noida, best acting classes in delhi">
<meta name="description" content="Enroll in one of the Best Singing School in Noida. T-Series StageWorks is the best singing school in Delhi">
<?php } else if($page=="basics-of-modelling"){ ?>
<title>T-Series Stage Works &bull; Programs &bull; Basics of Modelling</title>
<meta name="keywords" content="Tseries Modelling academy, Tseries Dance academy, Tseries Modelling school, acting school in noida, singing school in noida, best acting school in delhi, best acting school in noida, best singing school in noida, best singing school in delhi, best acting academy in noida, best acting academy in delhi, best singing school in noida, best singing school in delhi, best dancing school in noida, best dancing school in delhi, acting school in delhi, singing school in delhi, best acting class in noida, best acting classes in delhi">
<meta name="description" content="Enroll At T-Series StageWorks which is one of the Best Modelling Academy in Noida. T-Series StageWorks is the best Modelling academy in Delhi ">
<?php } else if($page=="basics-of-dance"){ ?>
<title>T-Series Stage Works &bull; Programs &bull; Basics of Dance</title>
<meta name="keywords" content="T-Series, tseries acting academy, Tseries singing academy, Tseries Modelling academy, Tseries Dance academy, tseries photography academy, tseries instrumental academy, tseries acting school, Tseries singing school, Tseries Modelling school, Tseries Dance school, tseries photography school, tseries instrumental school, tseries music school, acting school in noida, singing school in noida, best acting school in delhi, best acting school in noida, best singing school in noida, best singing school in delhi, best acting academy in noida, best acting academy in delhi, best singing school in noida, best singing school in delhi, best dancing school in noida, best dancing school in delhi, acting school in delhi, singing school in delhi, best acting class in noida, best acting classes in delhi">
<meta name="description" content="With academic direction from the charismatic and super-talented Ahmed Khan, Tseries StageWorks which is one of the best dancing academy in noida provide platforms for the students.">
<?php } else if($page=="basics-of-photography"){ ?>
<title>T-Series Stage Works &bull; Programs &bull; Basics of Photography</title>
<meta name="keywords" content="T-Series, tseries acting academy, Tseries singing academy, Tseries Modelling academy, Tseries Dance academy, tseries photography academy, tseries instrumental academy, tseries acting school, Tseries singing school, Tseries Modelling school, Tseries Dance school, tseries photography school, tseries instrumental school, tseries music school, acting school in noida, singing school in noida, best acting school in delhi, best acting school in noida, best singing school in noida, best singing school in delhi, best acting academy in noida, best acting academy in delhi, best singing school in noida, best singing school in delhi, best dancing school in noida, best dancing school in delhi, acting school in delhi, singing school in delhi, best acting class in noida, best acting classes in delhi">
<meta name="description" content="The course is structured by stalwarts of Indian photography and introduces the students to basic concepts of photography such as composition, lighting, framing etc. The course provides an excellent opportunity for amateur to learn and hone the skills of photography.">
<?php } else if($page=="basics-of-guitar"){ ?>
<title>T-Series Stage Works &bull; Programs &bull; Basics of Guitar</title>
<meta name="keywords" content="T-Series, tseries acting academy, Tseries singing academy, Tseries Modelling academy, Tseries Dance academy, tseries photography academy, tseries instrumental academy, tseries acting school, Tseries singing school, Tseries Modelling school, Tseries Dance school, tseries photography school, tseries instrumental school, tseries music school, acting school in noida, singing school in noida, best acting school in delhi, best acting school in noida, best singing school in noida, best singing school in delhi, best acting academy in noida, best acting academy in delhi, best singing school in noida, best singing school in delhi, best dancing school in noida, best dancing school in delhi, acting school in delhi, singing school in delhi, best acting class in noida, best acting classes in delhi">
<meta name="description" content="">
<?php } else if($page=="word-of-mouth"){ ?>
<title>T-Series Stage Works &bull; Word of Mouth</title>
<meta name="keywords" content="T-Series, tseries acting academy, Tseries singing academy, Tseries Modelling academy, Tseries Dance academy, tseries photography academy, tseries instrumental academy, tseries acting school, Tseries singing school, Tseries Modelling school, Tseries Dance school, tseries photography school, tseries instrumental school, tseries music school, acting school in noida, singing school in noida, best acting school in delhi, best acting school in noida, best singing school in noida, best singing school in delhi, best acting academy in noida, best acting academy in delhi, best singing school in noida, best singing school in delhi, best dancing school in noida, best dancing school in delhi, acting school in delhi, singing school in delhi, best acting class in noida, best acting classes in delhi">
<meta name="description" content="">
<?php }  else if($page=="gallery"){ ?>
<title>T-Series Stage Works &bull; Gallery</title>
<meta name="keywords" content="T-Series, tseries acting academy, Tseries singing academy, Tseries Modelling academy, Tseries Dance academy, tseries photography academy, tseries instrumental academy, tseries acting school, Tseries singing school, Tseries Modelling school, Tseries Dance school, tseries photography school, tseries instrumental school, tseries music school, acting school in noida, singing school in noida, best acting school in delhi, best acting school in noida, best singing school in noida, best singing school in delhi, best acting academy in noida, best acting academy in delhi, best singing school in noida, best singing school in delhi, best dancing school in noida, best dancing school in delhi, acting school in delhi, singing school in delhi, best acting class in noida, best acting classes in delhi">
<meta name="description" content="">
<?php } else { ?>

<title>T-Series Stage Works</title>
<meta name="keywords" content="T-Series, tseries acting academy, Tseries singing academy, Tseries Modelling academy, Tseries Dance academy, tseries photography academy, tseries instrumental academy, tseries acting school, Tseries singing school, Tseries Modelling school, Tseries Dance school, tseries photography school, tseries instrumental school, tseries music school, acting school in noida, singing school in noida, best acting school in delhi, best acting school in noida, best singing school in noida, best singing school in delhi, best acting academy in noida, best acting academy in delhi, best singing school in noida, best singing school in delhi, best dancing school in noida, best dancing school in delhi, acting school in delhi, singing school in delhi, best acting class in noida, best acting classes in delhi">
<meta name="description" content="">

<?php } ?>